version: '3.5'
services:
  site_b:
    container_name: site_b
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/var/www/html/index.html
    ports:
      - 81:80
    restart: always
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    name: nginx-proxy
